# TRATAMENTO DE EXCESS√ÉO COM TRY E EXCEPT
try:
    num = int(input("Digite um numero inteiro: "))

except:
     print("ValueError!")